version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    depends_on:
      - redis
    restart: on-failure
    environment:
      - HTTP_IP=0.0.0.0
      - HTTP_PORT=9000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
    tty: true
    networks:
      - app_network

  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge